/**
 * @name ActionConstants or Action Types
 */
export const ACTION_TYPES = {
	FETCH_LATEST_REQUEST: "FETCH_LATEST_REQUEST",
	FETCH_LATEST_FAIL: "FETCH_LATEST_FAIL",
	FETCH_LATEST_SUCCESS: "FETCH_LATEST_SUCCESS",
	FETCH_SYMBOLS_REQUEST: "FETCH_SYMBOLS_REQUEST",
	FETCH_SYMBOLS_FAIL: "FETCH_SYMBOLS_FAIL",
	FETCH_SYMBOLS_SUCCESS: "FETCH_SYMBOLS_SUCCESS",
};
